apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
