version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring123

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - employee-network


  backend:
    build:
      context: ./backend

    container_name: springboot

    restart: always

    depends_on:
      - mysql

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: spring

    networks:
      - employee-network


  frontend:
    build:
      context: ./frontend

    container_name: react

    restart: always

    depends_on:
      - backend

    ports:
      - "5174:5174"

    networks:
      - employee-network


volumes:
  mysql-data:


networks:
  employee-network:
