apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: employee_db
  MYSQL_USER: spring
  MYSQL_PASSWORD: spring123