apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
